### PR TITLE
Black Banner logo - looks quality

### PR DESCRIPTION
**Pull request by Ticketedmoon**
From the array of banners you gave us, I went with the black and white one. Looks great.

### CODE REVIEW

**Comment by hasan356** [comment]
@ShaneCreedon  Thanks for the effort, but can you please align it to the right, it currently overlaps logo.

[image](https://i.imgur.com/qZBqvl5.png)

**Comment by Ticketedmoon** [comment]
@hasan356 Oh right, sure thing

**Comment by Ticketedmoon** [comment]
@hasan356 This is done.

**Comment by vishvanath45** [comment]
@ShaneCreedon  can you please link `Fork me on Github` to `https://github.com/vishvanath45/CodeHike` since this branch would be updated at all times.

**Comment by Ticketedmoon** [comment]
This is done.

**Comment by vishvanath45** [comment]
Merged!, @ShaneCreedon your effort is much appreciated. 

Keep Contributing to open source. :D

**Comment by Ticketedmoon** [comment]
@vishvanath45 My pleasure, Thank you ^^

**Pull request merged**
